### PR TITLE
escaping quotes in strings

### LINKED ISSUE #1: quotes in strings are not escaped
Expected result:
```
q).json.json "here is my \"quote\""
"{ \"atom\": \"here is my \\\"quote\\\"\" }"
```
Actual result:
```
q).json.json "here is my \"quote\""
"{ \"atom\": \"here is my \"quote\"\" }"
```

which results in "Uncaught SyntaxError: Unexpected token q in JSON at position 23"

### PR DESCRIPTION
**Pull request by mkst**
fixes #1

### CODE REVIEW

**Comment by nugend** [comment]
Do you think you could add a test case for this?

**Comment by mkst** [comment]
not sure how you wanted it - hopefully that's simple enough to demonstrate the change :)

**Comment by nugend** [comment]
Oh I feel very bad. I had forgotten that I didn't originally write a test suite for this library. I'll accept the PR for now and add a test suite when I have a chance.

Out of curiosity, are you using this code? KX added a built in json output into the language a few years back.

**Comment by mkst** [comment]
I am... I inherited a kdb project which included your library but I've only recently started using it - I wasnt aware of it being built in, but just stumbled across http://code.kx.com/wiki/Cookbook/Websocket so I'll have a look at the json.k in the morning :) thanks!

**Pull request merged**
